/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugasbesarpbo;

import interfaceSystem.controllerRencanaBudget;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static tugasbesarpbo.koneksiDatabase.mysqlconfig;
/**
 *
 * @author Fauzi
 */
public class formRencanaBudget extends javax.swing.JFrame {
private rencanaBudget database;
int idRb;
String kategoriRb;
String tanggalAwal;
String tanggalAkhir;
String bulanRencana;
float jumlahRencana;
    
    /**
     * Creates new form formRencanaBudget
     */
    public formRencanaBudget() {
        initComponents();
        readRencanaBudget();
    }

    private void kosong(){
        formId.setText(null);
        cb_rb.setSelectedIndex(0);
        formBulan.setText(null);
        formTanggalAwal.setText(null);
        formTanggalAkhir.setText(null);
        formBulan.setText(null);
    }
    
//     private void inputRencanaBudget() {
//            try {
//                String kategori = this.cb_rb.getSelectedItem().toString();
//                 float jumlahBudget = Float.parseFloat(this.formJumlah.getText());
//                String tanggalAwal =this.formTanggalAwal.getText();
//                String tanggalAkhir =this.formTanggalAkhir.getText();
//                String bulan = this.formBulan.getText();
//               
//                database.inputPemasukan(kategori, jumlahBudget, bulan, tanggalAwal, tanggalAkhir);
//                JOptionPane.showMessageDialog(rootPane, "Data Berhasil Masuk");
//            } catch (Exception e){
//                JOptionPane.showMessageDialog(rootPane, "Data Belum Diisi" + e.getMessage());
//            }
//    }
     
//     private void updateRencanaBudget(){
//        try {
//            
//              String sql = " UPDATE rencanaBudget SET  kategori = '" + cb_rb.getSelectedItem() + "', jumlahBudget = '" + formJumlah.getText() +"', tglAwal_RB = '" + formTanggalAwal.getText() + "', tglAkhir_RB = '" + formTanggalAkhir.getText() + "' WHERE id_rencanaBudget = '" + formId.getText() + "'";
//            java.sql.Connection conn = new koneksiDatabase().configDB();
//            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
//            pst.execute();
//            JOptionPane.showMessageDialog(rootPane, "data berhasil di update");
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(rootPane, "data gagal di update" + e.getMessage());
//        }
//        readRencanaBudget();
//        kosong();
//    }
     
//     private void deleteRencanaBudget(){
//        try {
//            String sql ="delete from rencanaBudget where id_rencanaBudget = '"+formId.getText()+"'";
//            java.sql.Connection conn = new koneksiDatabase().configDB();
//            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
//            pst.execute();
//            JOptionPane.showMessageDialog(this, "berhasil di hapus");
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, e.getMessage());
//        }
//        readRencanaBudget();
//        kosong();
//    }
     
            private void readRencanaBudget(){
         DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID Rencana Budget");
            model.addColumn("Kategori");
            model.addColumn("Jumlah Pemasukan");
            model.addColumn("Tanggal Awal");
            model.addColumn("Tanggal Akhir");
            model.addColumn("Bulan");

        try {
            String sql = "SELECT * FROM `rencanabudget`";
            java.sql.Connection conn = new koneksiDatabase().configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {            
            model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3), res.getString(5), res.getString(6), res.getString(4)});
        }
            tableRencanaBudget.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        formId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cb_rb = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        formBulan = new javax.swing.JTextField();
        formJumlah = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        formTanggalAwal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        formTanggalAkhir = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        buttonHapus = new javax.swing.JButton();
        buttonBatal = new javax.swing.JButton();
        buttonSimpan = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRencanaBudget = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        buttonKembali = new javax.swing.JMenuItem();
        buttonKeluar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("FORM RENCANA BUDGET");

        jLabel5.setText("ID RENCANA ");

        formId.setEnabled(false);
        formId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formIdActionPerformed(evt);
            }
        });

        jLabel4.setText("Kategori Rencana Budget");

        cb_rb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Kategori Rencana --", "Investasi", "Bisnis", "Sehari hari", " " }));
        cb_rb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_rbActionPerformed(evt);
            }
        });

        jLabel6.setText("Jumlah Budget");

        formBulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formBulanActionPerformed(evt);
            }
        });

        formJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formJumlahActionPerformed(evt);
            }
        });

        jLabel7.setText("Tanggal awal");

        formTanggalAwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formTanggalAwalActionPerformed(evt);
            }
        });

        jLabel8.setText("Tanggal Akhir");

        formTanggalAkhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formTanggalAkhirActionPerformed(evt);
            }
        });

        jLabel9.setText("Bulan Pengeluaran");

        buttonHapus.setText("Hapus");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        buttonBatal.setBackground(new java.awt.Color(220, 53, 69));
        buttonBatal.setForeground(new java.awt.Color(255, 255, 255));
        buttonBatal.setText("Batal");
        buttonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBatalActionPerformed(evt);
            }
        });

        buttonSimpan.setBackground(new java.awt.Color(25, 135, 84));
        buttonSimpan.setForeground(new java.awt.Color(255, 255, 255));
        buttonSimpan.setText("Simpan");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        editButton.setText("Update");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        tableRencanaBudget.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Rencana Budget", "Kategori", "Tanggal Awal", "Tanggal Akhir", "Bulan", "Jumlah"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableRencanaBudget.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableRencanaBudgetMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableRencanaBudget);
        if (tableRencanaBudget.getColumnModel().getColumnCount() > 0) {
            tableRencanaBudget.getColumnModel().getColumn(0).setResizable(false);
            tableRencanaBudget.getColumnModel().getColumn(1).setResizable(false);
            tableRencanaBudget.getColumnModel().getColumn(3).setResizable(false);
            tableRencanaBudget.getColumnModel().getColumn(4).setResizable(false);
            tableRencanaBudget.getColumnModel().getColumn(5).setResizable(false);
        }

        jMenu1.setText("Menu");

        buttonKembali.setText("Kembali");
        buttonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKembaliActionPerformed(evt);
            }
        });
        jMenu1.add(buttonKembali);

        buttonKeluar.setText("Keluar");
        buttonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKeluarActionPerformed(evt);
            }
        });
        jMenu1.add(buttonKeluar);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(310, 310, 310)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(210, 210, 210)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cb_rb, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(formId, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(formJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(196, 196, 196)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(editButton)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(buttonHapus)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(buttonBatal)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(buttonSimpan))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(formTanggalAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel7))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(formTanggalAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel8))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(formBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel9)))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_rb, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(11, 11, 11)
                .addComponent(formJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formTanggalAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formTanggalAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKeluarActionPerformed
       System.exit(0);
    }//GEN-LAST:event_buttonKeluarActionPerformed

    private void buttonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliActionPerformed
        Home back = new Home();
        back.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonKembaliActionPerformed

    private void formIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formIdActionPerformed
        formId.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_formIdActionPerformed

    private void cb_rbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_rbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_rbActionPerformed

    private void formBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formBulanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formBulanActionPerformed

    private void formJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formJumlahActionPerformed

    private void formTanggalAwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formTanggalAwalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formTanggalAwalActionPerformed

    private void formTanggalAkhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formTanggalAkhirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formTanggalAkhirActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
       idRb =Integer.parseInt(formId.getText());
       interfaceSystem.interfaceRencanaBudget rencanaBudget = new controllerRencanaBudget();
       rencanaBudget.delete(idRb);
       readRencanaBudget();
        kosong();
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void buttonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBatalActionPerformed
        kosong();
    }//GEN-LAST:event_buttonBatalActionPerformed

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
      
        kategoriRb = cb_rb.getSelectedItem().toString();
        tanggalAwal = formTanggalAwal.getText();
        tanggalAkhir = formTanggalAkhir.getText();
        bulanRencana = formBulan.getText();
        jumlahRencana = Float.parseFloat(formJumlah.getText());
        
        interfaceSystem.interfaceRencanaBudget rencanaBudget = new controllerRencanaBudget();
        rencanaBudget.input(kategoriRb, tanggalAwal, tanggalAkhir ,jumlahRencana ,bulanRencana );
        readRencanaBudget();
        kosong();
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        idRb =Integer.parseInt(formId.getText());
        kategoriRb = cb_rb.getSelectedItem().toString();
        tanggalAwal = formTanggalAwal.getText();
        tanggalAkhir = formTanggalAkhir.getText();
        bulanRencana = formBulan.getText();
        jumlahRencana = Float.parseFloat(formJumlah.getText());
        interfaceSystem.interfaceRencanaBudget rencanaBudget = new controllerRencanaBudget();
        rencanaBudget.update(idRb, kategoriRb,tanggalAwal,tanggalAkhir,jumlahRencana, bulanRencana);
        readRencanaBudget();
        kosong();
        // TODO add your handling code here:
    }//GEN-LAST:event_editButtonActionPerformed

    private void tableRencanaBudgetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableRencanaBudgetMouseClicked
        int baris = tableRencanaBudget.rowAtPoint(evt.getPoint());
        String id = tableRencanaBudget.getValueAt(baris, 0).toString();
        formId.setText(id);
        String kategori = tableRencanaBudget.getValueAt(baris, 1).toString();
        cb_rb.setSelectedItem(kategori);
        String jumlahRencanaBudget = tableRencanaBudget.getValueAt(baris, 2).toString();
        formJumlah.setText(String.valueOf(jumlahRencanaBudget));
        String tglAwal = tableRencanaBudget.getValueAt(baris, 3).toString();
        formTanggalAwal.setText(tglAwal);
        String tglAkhir = tableRencanaBudget.getValueAt(baris, 4).toString();
        formTanggalAkhir.setText(tglAkhir);
        String bulan = tableRencanaBudget.getValueAt(baris, 5).toString();
        formBulan.setText(bulan);
    }//GEN-LAST:event_tableRencanaBudgetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formRencanaBudget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formRencanaBudget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formRencanaBudget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formRencanaBudget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formRencanaBudget().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBatal;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JMenuItem buttonKeluar;
    private javax.swing.JMenuItem buttonKembali;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JComboBox<String> cb_rb;
    private javax.swing.JButton editButton;
    private javax.swing.JTextField formBulan;
    private javax.swing.JTextField formId;
    private javax.swing.JTextField formJumlah;
    private javax.swing.JTextField formTanggalAkhir;
    private javax.swing.JTextField formTanggalAwal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableRencanaBudget;
    // End of variables declaration//GEN-END:variables
}
