/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugasbesarpbo;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static tugasbesarpbo.koneksiDatabase.mysqlconfig;
/**
 *
 * @author Fauzi
 */
public class formPengeluaran extends javax.swing.JFrame {
private pengeluaran database;
int id_pengeluaran;
String catatanPengeluaran;
String tanggal;
String kategori;
String bulan;
float jumlahPengeluaran;


    /**
     * Creates new form formPengeluaran
     */
    public formPengeluaran() {
        initComponents();
        readPengeluaran();
    }
    
    private void kosong(){
        formId.setText(null);
        formCatatan.setText(null);
        formBulan.setText(null);
        formTanggal.setText(null);
        cb_pengeluaran.setSelectedIndex(0);
        formJumlah.setText(null);  
    }

     
       private void readPengeluaran(){
         DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID Pengeluaran");
            model.addColumn("Catatan");
            model.addColumn("Kategori");
            model.addColumn("Tanggal");
            model.addColumn("Bulan");
            model.addColumn("Jumlah Pemasukan");

        try {
            String sql = "SELECT * FROM `pengeluaran`";
            java.sql.Connection conn = new koneksiDatabase().configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {            
            model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(4), res.getString(5), res.getString(3), res.getString(6)});
        }
            tablePengeluaran.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        formCatatan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        formId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        formBulan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        formTanggal = new javax.swing.JTextField();
        editButton = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        buttonBatal = new javax.swing.JButton();
        buttonSimpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePengeluaran = new javax.swing.JTable();
        cb_pengeluaran = new javax.swing.JComboBox<>();
        formJumlah = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        buttonKembali = new javax.swing.JMenuItem();
        buttonKeluar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("FORM PENGELUARAN");

        jLabel3.setText("Catatan Pengeluaran");

        formCatatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formCatatanActionPerformed(evt);
            }
        });

        jLabel5.setText("ID PENGELUARAN");

        formId.setEnabled(false);
        formId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formIdActionPerformed(evt);
            }
        });

        jLabel4.setText("Kategori Pengeluaran");

        jLabel6.setText("Jumlah Pengeluaran");

        jLabel7.setText("Tanggal Pengeluaran");

        formTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formTanggalActionPerformed(evt);
            }
        });

        editButton.setText("Update");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        buttonHapus.setText("Hapus");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        buttonBatal.setBackground(new java.awt.Color(220, 53, 69));
        buttonBatal.setForeground(new java.awt.Color(255, 255, 255));
        buttonBatal.setText("Batal");
        buttonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBatalActionPerformed(evt);
            }
        });

        buttonSimpan.setBackground(new java.awt.Color(25, 135, 84));
        buttonSimpan.setForeground(new java.awt.Color(255, 255, 255));
        buttonSimpan.setText("Simpan");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        tablePengeluaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID PENGELUARAN", "Catatan", "Tanggal ", "Bulan ", "Jumlah "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePengeluaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePengeluaranMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePengeluaran);

        cb_pengeluaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Kategori Pengeluaran --", "Pengeluaran Harian", "Pengeluaran Mingguan", "Pengeluaran Bulanan", " " }));
        cb_pengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_pengeluaranActionPerformed(evt);
            }
        });

        formJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formJumlahActionPerformed(evt);
            }
        });

        jLabel8.setText("Bulan Pengeluaran");

        jMenu1.setText("Menu");

        buttonKembali.setText("Kembali");
        buttonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKembaliActionPerformed(evt);
            }
        });
        jMenu1.add(buttonKembali);

        buttonKeluar.setText("Keluar");
        buttonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKeluarActionPerformed(evt);
            }
        });
        jMenu1.add(buttonKeluar);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(211, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(editButton)
                                        .addGap(8, 8, 8)
                                        .addComponent(buttonHapus))
                                    .addComponent(jLabel7)
                                    .addComponent(formTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buttonBatal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonSimpan))
                                    .addComponent(formBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)))
                            .addComponent(formCatatan, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(cb_pengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(formJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(formId, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(113, 113, 113))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formCatatan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_pengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(formBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(formTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKeluarActionPerformed
       System.exit(0);
    }//GEN-LAST:event_buttonKeluarActionPerformed

    private void buttonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliActionPerformed
        Home back = new Home();
        back.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonKembaliActionPerformed

    private void formCatatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formCatatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formCatatanActionPerformed

    private void formIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formIdActionPerformed
        formId.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_formIdActionPerformed

    private void formTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formTanggalActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        id_pengeluaran = Integer.parseInt(formId.getText());
        catatanPengeluaran = formCatatan.getText();
        tanggal = formTanggal.getText();
        kategori = cb_pengeluaran.getSelectedItem().toString();
        bulan = formBulan.getText().toLowerCase();
        jumlahPengeluaran = Float.parseFloat(formJumlah.getText());
        pengeluaran pl = new pengeluaran(id_pengeluaran, catatanPengeluaran, tanggal, bulan, kategori, jumlahPengeluaran);
        pl.updatePengeluaran(id_pengeluaran,catatanPengeluaran, tanggal, bulan, kategori, jumlahPengeluaran);
        readPengeluaran();
        kosong();
    }//GEN-LAST:event_editButtonActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        id_pengeluaran = Integer.parseInt(formId.getText());
        pengeluaran pl = new pengeluaran(id_pengeluaran, catatanPengeluaran, tanggal, bulan, kategori, jumlahPengeluaran);
        pl.deletePengeluaran(id_pengeluaran);
        readPengeluaran();
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void buttonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBatalActionPerformed
        kosong();
    }//GEN-LAST:event_buttonBatalActionPerformed

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
      
        catatanPengeluaran = formCatatan.getText();
        tanggal = formTanggal.getText();
        kategori = cb_pengeluaran.getSelectedItem().toString();
        bulan = formBulan.getText().toLowerCase();
        jumlahPengeluaran = Float.parseFloat(formJumlah.getText());
        pengeluaran pl = new pengeluaran(WIDTH, catatanPengeluaran, tanggal, bulan, kategori, jumlahPengeluaran);
        pl.inputPengeluaran(catatanPengeluaran, tanggal, bulan, kategori, jumlahPengeluaran);
        readPengeluaran();
        kosong();
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void tablePengeluaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePengeluaranMouseClicked
        int baris = tablePengeluaran.rowAtPoint(evt.getPoint());
        String id = tablePengeluaran.getValueAt(baris, 0).toString();
        formId.setText(id);
        String catatan = tablePengeluaran.getValueAt(baris, 1).toString();
        formCatatan.setText(catatan);
        
        String tanggalPengeluaran = tablePengeluaran.getValueAt(baris, 3).toString();
        formTanggal.setText(tanggalPengeluaran);
        
        String bulanPengeluaran = tablePengeluaran.getValueAt(baris, 4).toString();
        formBulan.setText(bulanPengeluaran);
        
        String kategoriPengeluaran = tablePengeluaran.getValueAt(baris, 2).toString();
        cb_pengeluaran.setSelectedItem(kategoriPengeluaran);
        
        String jumlah = tablePengeluaran.getValueAt(baris, 5).toString();
        formJumlah.setText(String.valueOf(jumlah));
    }//GEN-LAST:event_tablePengeluaranMouseClicked

    private void cb_pengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_pengeluaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_pengeluaranActionPerformed

    private void formJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formJumlahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formPengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formPengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formPengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formPengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formPengeluaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBatal;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JMenuItem buttonKeluar;
    private javax.swing.JMenuItem buttonKembali;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JComboBox<String> cb_pengeluaran;
    private javax.swing.JButton editButton;
    private javax.swing.JTextField formBulan;
    private javax.swing.JTextField formCatatan;
    private javax.swing.JTextField formId;
    private javax.swing.JTextField formJumlah;
    private javax.swing.JTextField formTanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePengeluaran;
    // End of variables declaration//GEN-END:variables
}
