/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugasbesarpbo;

/**
 *
 * @author Fauzi
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form tugasBesarGUI
     */
    public Home() {
        initComponents();
        menuKembali.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buttonPemasukan = new javax.swing.JToggleButton();
        buttonDanaDarurat = new javax.swing.JToggleButton();
        buttonLaporan = new javax.swing.JToggleButton();
        buttonRencanaBudget = new javax.swing.JToggleButton();
        buttonAset = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        buttonPengeluaran = new javax.swing.JToggleButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuKembali = new javax.swing.JMenuItem();
        menuKeluar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasbesarpbo/laporan.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 90, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasbesarpbo/aset.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        jLabel7.setBackground(new java.awt.Color(28, 116, 109));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasbesarpbo/rencana budget.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasbesarpbo/dana darurat.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fauzi\\OneDrive\\Documents\\gambarPbo\\pemasukan.png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        buttonPemasukan.setBackground(new java.awt.Color(16, 26, 36));
        buttonPemasukan.setForeground(new java.awt.Color(16, 26, 36));
        buttonPemasukan.setBorder(null);
        buttonPemasukan.setBorderPainted(false);
        buttonPemasukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPemasukanActionPerformed(evt);
            }
        });
        getContentPane().add(buttonPemasukan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 80, 90));

        buttonDanaDarurat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDanaDaruratActionPerformed(evt);
            }
        });
        getContentPane().add(buttonDanaDarurat, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 77, 80));

        buttonLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLaporanActionPerformed(evt);
            }
        });
        getContentPane().add(buttonLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 70, 90));

        buttonRencanaBudget.setBackground(new java.awt.Color(28, 116, 109));
        buttonRencanaBudget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRencanaBudgetActionPerformed(evt);
            }
        });
        getContentPane().add(buttonRencanaBudget, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 70, 90));

        buttonAset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAsetActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAset, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 80, 80));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel1.setText("Laporan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setText("Dana Darurat");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, -1));

        jPanel1.setBackground(new java.awt.Color(62, 112, 133));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 686, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 690, 60));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasbesarpbo/pengeluaran.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        buttonPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPengeluaranActionPerformed(evt);
            }
        });
        getContentPane().add(buttonPengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 77, 90));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setText("Pengeluaran");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setText("Pemasukan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel11.setText("Rencana Budget");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, -1, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel12.setText("Aset");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, -1, -1));

        jMenu1.setText("Menu");

        menuKembali.setText("Kembali");
        menuKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKembaliActionPerformed(evt);
            }
        });
        jMenu1.add(menuKembali);

        menuKeluar.setText("Keluar");
        menuKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKeluarActionPerformed(evt);
            }
        });
        jMenu1.add(menuKeluar);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKembaliActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_menuKembaliActionPerformed

    private void menuKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKeluarActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuKeluarActionPerformed

    private void buttonPemasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPemasukanActionPerformed
        formPemasukan next = new formPemasukan();
        next.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonPemasukanActionPerformed

    private void buttonPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPengeluaranActionPerformed
       formPengeluaran next = new formPengeluaran();
        next.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonPengeluaranActionPerformed

    private void buttonDanaDaruratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDanaDaruratActionPerformed
        formDanaDarurat next = new formDanaDarurat();
        next.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonDanaDaruratActionPerformed

    private void buttonRencanaBudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRencanaBudgetActionPerformed
        formRencanaBudget next = new formRencanaBudget();
        next.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonRencanaBudgetActionPerformed

    private void buttonAsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAsetActionPerformed
        formAset next = new formAset();
        next.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonAsetActionPerformed

    private void buttonLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLaporanActionPerformed
        laporan next = new laporan();
        next.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonLaporanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton buttonAset;
    private javax.swing.JToggleButton buttonDanaDarurat;
    private javax.swing.JToggleButton buttonLaporan;
    private javax.swing.JToggleButton buttonPemasukan;
    private javax.swing.JToggleButton buttonPengeluaran;
    private javax.swing.JToggleButton buttonRencanaBudget;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menuKeluar;
    private javax.swing.JMenuItem menuKembali;
    // End of variables declaration//GEN-END:variables
}
